api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    collection:
        pagination:
            enabled: false
            items_per_page: 5
            client_enabled: true
            client_items_per_page: true
            
    # http_cache:
    #     -   invalidation:
    #         -   enabled: true
    #         -   varnish_urls: ['%env(VARNISH_URL)%']
    #     -   max_age: 0
    #     -   shared_max_age: 3600
    #     -   vary: ['Content-Type', 'Authorization', 'Origin']
    #     -   public: true
    